package com.browserstack.automate.ci.common;

public interface BrowserStackEnvVars {
    String BROWSERSTACK_USER = "BROWSERSTACK_USER";
    String BROWSERSTACK_USERNAME = "BROWSERSTACK_USERNAME";
    String BROWSERSTACK_ACCESSKEY = "BROWSERSTACK_ACCESSKEY";
    String BROWSERSTACK_ACCESS_KEY = "BROWSERSTACK_ACCESS_KEY";
    String BROWSERSTACK_LOCAL = "BROWSERSTACK_LOCAL";
    String BROWSERSTACK_LOCAL_IDENTIFIER = "BROWSERSTACK_LOCAL_IDENTIFIER";
    String BROWSERSTACK_BUILD = "BROWSERSTACK_BUILD";
    String BROWSERSTACK_BUILD_NAME = "BROWSERSTACK_BUILD_NAME";
    String BROWSERSTACK_APP_ID = "BROWSERSTACK_APP_ID";
    String BROWSERSTACK_RERUN = "BROWSERSTACK_RERUN";
    String BROWSERSTACK_RERUN_TESTS = "BROWSERSTACK_RERUN_TESTS";
}
